### ISSUE TITLE
[1.00] Video Settings menu is broken?

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#102]
I'm unsure as to why this is happening, but the video settings menu for any builds of 1.00 Sonic Mania are broken.

![image](https://user-images.githubusercontent.com/24783625/187056263-c25f145a-4db4-4710-aba4-3b10bad616e1.png)

For comparison, this is what 1.03 looks like:

![image](https://user-images.githubusercontent.com/24783625/187056276-4778bdba-14ca-4f77-9790-1220fe791825.png)

i assume the menu is supposed to look like the former instead of the latter, but the options for screen size and vsync are very broken.

**Comment by Rubberduckycooly** [comment]
removed those objects in f6134aa2215cd21c0f8d19cd07784728b93af6fe, they weren't added until 1.03 (PC release)
