### ISSUE TITLE
Level icon changing pallettes when switching to another level.

### ISSUE THREAD

**Issue by Swapnekokitten** [Rubberduckycooly/Sonic-Mania-Decompilation#105]
![Screenshot_20220828-195501_RSDKv5](https://user-images.githubusercontent.com/105176896/187090385-307ec360-6168-4a48-84de-025d8233e99f.jpg)
When completing a stage in time attack going to hover on another stage the previous stage icon palette changes for example look at this.

**Comment by Rubberduckycooly** [comment]
should be fixed in 50c35c87479977a7a75651897f1fc91e1e3f015e, please re-open this if it isn't.

**Comment by Swapnekokitten** [comment]
REOPEN THIS ISSUE

**Comment by Swapnekokitten** [comment]
I just updated the build and it seems like it did nothing please comment back and open the issue again
