### ISSUE TITLE
When changing to another act when finishing first act 1 changes to green hill.

### ISSUE THREAD

**Issue by Swapnekokitten** [Rubberduckycooly/Sonic-Mania-Decompilation#106]
When changing to second act for example after finishing act 1 it changes to green hill here is some footage of the known bug.

**Comment by Swapnekokitten** [comment]
Uploading Screen_Recording_20220828_195918_RSDKv5.mp4…

**Comment by Swapnekokitten** [comment]
https://youtu.be/NM_nHczD3tY

**Comment by Rubberduckycooly** [comment]
fixed in 50c35c87479977a7a75651897f1fc91e1e3f015e
