### ISSUE TITLE
Screen with wrong resolutions and controls not appearing

### ISSUE THREAD

**Issue by Wonska** [Rubberduckycooly/Sonic-Mania-Decompilation#109]
![2022_08_30_20 29 14](https://user-images.githubusercontent.com/112523934/187562023-8783b41b-f8e8-43c5-acf4-23152a0759fe.jpg)

**Comment by Wonska** [comment]
I tried everything I could, but it still looks like that, please help me

**Comment by LittlePlanetCD** [comment]
these are known issues already, and have been reported before.

mainly reported at https://github.com/Rubberduckycooly/RSDKv5-Decompilation/issues/44

**Comment by Wonska** [comment]
How do I fix it then

**Comment by Luccas7383** [comment]
> How do I fix it then

man has no solutions
