### ISSUE TITLE
Partner Sonic in Encore Mode can Drop Dash.

### ISSUE THREAD

**Issue by HarperMarieRose** [Rubberduckycooly/Sonic-Mania-Decompilation#110]
When in control of another character in Encore Mode, Sonic is still able to Drop Dash. This doesn't happen on the Steam version. Tested on v5u dx9 64-bit on the latest build.

https://user-images.githubusercontent.com/77728222/187675167-55e5cc2b-5a8d-4411-933e-2d8bcea0aaa4.mp4

**Comment by breakthetargets** [comment]
Can reproduce.

**Comment by Rubberduckycooly** [comment]
fixed in b3eb7291d9bc62fd1f1f713003a520a4b33b62f6
