### ISSUE TITLE
[1.00] Incorrect Debug Mode special stage ring behavior

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#111]
For some reason, spawning and entering a Big Ring object causes the game to softlock, when on the original 1.00, it would enter the special stage as intended.

https://user-images.githubusercontent.com/24783625/188028932-662d33f7-5ab3-48b9-a25d-80f5e6564a8c.mp4

**Comment by Rubberduckycooly** [comment]
fixed in ea9b20b7687499390e565e64af72f38764fe8bb9
