### ISSUE TITLE
[1.00] Incorrect UI Dialog for replace key prompt (??????)

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#112]
For some reason, when rebinding keys in 1.00, it causes the UI prompt to pull random strings from the game
 (???)![unknown-76.png](https://user-images.githubusercontent.com/24783625/188028371-53337af5-a196-4d3b-8e3c-0547691c2b89.png)

![unknown-95.png](https://user-images.githubusercontent.com/24783625/188031553-68c0924e-d645-4f4f-99d1-b2eac24e8432.png)

It... Also seems to have a tendency to cause said strings that appear in other places to get deleted (??)

![unknown-145.png](https://user-images.githubusercontent.com/24783625/188028476-024045fe-f5b1-43d0-90e2-5311fffaa154.png)

**Comment by LittlePlanetCD** [comment]
okay, it also seems like that DA Garden just has issues with its strings as well in the last image.

i directly loaded into it and the "Select a Track" text was missing.

**Comment by Rubberduckycooly** [comment]
should be fixed in c7889564e03a1829f916f9066f777c9fe832b8c2
