### ISSUE TITLE
[All Versions] HCZ2 Eggman fight causes a hard freeze.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#115]
When beating the Eggman boss in Hydro City Act 2, the game just hard freezes. Unsure as to why.

![image](https://user-images.githubusercontent.com/24783625/188241266-b0a7674b-3aee-43dd-a1df-15050c07f39a.png)

**Comment by Rubberduckycooly** [comment]
fixed in 210351de97fa64a6e7dcdeba3089695ae0794931
