### ISSUE TITLE
(RSDKV5) can't wallclimb in CPZ2 after clipping through a wall

### ISSUE THREAD

**Issue by grindersky** [Rubberduckycooly/Sonic-Mania-Decompilation#116]
as seen here I did manage to successfully clip through a wall, but can't wallclimb like in the steam version
https://user-images.githubusercontent.com/31354929/188289021-4e8a1624-e3db-4677-910f-90ac2d95c4d5.mp4

here's how it is done normally by speedrunners (the video is kinda long, I apologize for that but that's the one I know)
https://youtu.be/QbWz7ZQdnVs?t=394

**Comment by Rubberduckycooly** [comment]
should be fixed in https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/bc2b2be867af1e9dc940f8c9aaf4b77dee2a0dd8
