### ISSUE TITLE
Mod Testing Results

### ISSUE THREAD

**Issue by MystiK791** [Rubberduckycooly/Sonic-Mania-Decompilation#119]
With the latest mod update, I tested a few different mods to see how well they'd function:

(Note: these were all tested on the PS Vita port, as I was curious to see how these mods would function on a non-Windows platform)

- **Any character mod** (such as Blazy Mix Plus): Partially functional, but any mods that have a custom moveset don't work due to them relying on DLL injection
- **Any stage mod**: Fully functional, as long as the stage doesn't use a DLL
- **Sonic Megamix Mania**: Somewhat functional. The title screen and custom menus work just fine, but character switching and (suprise suprise) custom movesets don't work at all. Neither do custom objects and enemies
- **Cooler Sonic Plus**: Arguably the simplest mod I tested, and it's mostly functional. I wasn't able to test it fully because I can't get Sonic Mania Plus working.

I wonder, if for the DLL mods, if it's possible to extract the scripts and assets from them and inject them another way for non-Windows platforms.

**Comment by MGRich** [comment]
Nice list! All of these mods should exhibit equal behavior on any platform with a mod loader. I will pin this just in case any mod-players wish to see if their mod is compatible or not.

All mods must have `TargetVersion=5` added to their mod.ini in the current public release build.

**Comment by MegAmi24** [comment]
DLL mods don't have scripts, it works entirely differently from S1/S2/CD. You have to recompile the mod's source code for the target platform, or in the case of Android, compile the mod with the game itself.

Also, DLL mods made for the Steam version of Mania won't work on the decomp, you'll have to remake the mod with GameAPI for it to work.
