### ISSUE TITLE
Platforms in Titanic Monarch don't behave correctly

### ISSUE THREAD

**Issue by TheAgamer554** [Rubberduckycooly/Sonic-Mania-Decompilation#122]
The 2 middle platforms don't balance properly and are stationary, issue happens on main
![imagen](https://user-images.githubusercontent.com/42060301/188849251-c95ce749-c4fe-4d31-906d-ef4ec120f13d.png)

**Comment by Rubberduckycooly** [comment]
fixed in 28380e75777c902c4fa49796b11be20b20bf28cb
