### ISSUE TITLE
(Request) Flatpak script ala Sonic 1/2 Decomp for Steam Deck users to be able to build with Plus support

### ISSUE THREAD

**Issue by Star-X555** [Rubberduckycooly/Sonic-Mania-Decompilation#123]
Tried building it myself on my Arch Linux tablet, but on Steam Deck using Maniatic launcher with a swapped Game.so it just comes up as a white screen, presumably because Arch Linux is further ahead of SteamOS update wise.

Obviously Steam Deck lacks the Base-devel package on its immutable filesystem, which rules out compiling through normal means too.

I'm terribly stupid when it comes to flatpaks, so a script that does the building for you would be greatly appreciated.

**Comment by Clownacy** [comment]
For cross-compiling to the Steam Deck, I use Debian. Its packages are old enough that binaries compiled on it will run on SteamOS.

**Comment by TheAgamer554** [comment]
if you follow these steps you should be able to compile it on the steam deck by using flatpak only [https://github.com/santiagocezar/rsdkv5-decomp-docs/blob/main/Linux.md#compiling-flatpak](https://github.com/santiagocezar/rsdkv5-decomp-docs/blob/main/Linux.md#compiling-flatpak)
