### ISSUE TITLE
[All Versions, including v5 and v5u] Flying Battery Zone incorrect physics behaviour.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#125]
Normally, in FBZ2, this object lets you ride it all the way to the next wall it hits, which the player latches onto that wall and goes down it.

![image](https://user-images.githubusercontent.com/24783625/189189979-059ec3f5-0f56-47f4-9f47-71d76d329e1e.png)

But on the decomp, the player does not latch onto the wall the object lands on sometimes, causing the player to "detach" 

![image](https://user-images.githubusercontent.com/24783625/189190122-bee96eb1-adb2-4aba-803a-a17f0f1d6bd0.png)

**Comment by Rubberduckycooly** [comment]
fixed in 51ab7ce412f294217cb5f3ec2e46a415155dda3e
