### ISSUE TITLE
[1.00] Knuckles Ledgeclimb bug doesn't exist (?)

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#129]
I was going through an old video A+Start made about bugs in Sonic Mania, because I wanted to test out what worked on the 1.00 version of the decomp (expecting it to be there).

For some reason, the Knuckles Ledgeclimb bug isn't working:

![ezgif-2-b3a27360b0](https://user-images.githubusercontent.com/24783625/190081273-b582ff5d-060b-43cb-af75-bf531f6de3c9.gif)

See A+Start's video if you wanna see other instances of this bug also happening on the console release build: https://youtu.be/nKfDxm-vkec?t=252

**Comment by Rubberduckycooly** [comment]
fixed in a6b2653465ad9bbf92cfe7d0477a9346efeea2ed
