### ISSUE TITLE
Time starts too soon in a stage

### ISSUE THREAD

**Issue by thegreenspirit** [Rubberduckycooly/Sonic-Mania-Decompilation#136]
The time starts way too soon when the title screen appears in the decomp. (i cannot crop the video so just stare at the time)

https://user-images.githubusercontent.com/111328261/192025682-1143986b-fd5e-4797-a0c1-50a14ceef799.mp4

https://user-images.githubusercontent.com/111328261/192026066-d77bdb4e-35d3-412a-ad46-c985ea0d2571.mp4

**Comment by Rubberduckycooly** [comment]
fixed in ff1183befba3d58dd8c5b3ab79b712f86c01d826
