### ISSUE TITLE
[Pre-Plus] TMZ2 last Portal to Boss goes into ERZ instead.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#138]
After doing all 4 of the portal sections in TMZ2 on Pre-Plus, the last portal opens, and it's supposed to take you to TMZ3 / the last boss of TMZ.

But, instead, it takes you to Egg Reverie Zone, the true final boss.

**Comment by Rubberduckycooly** [comment]
fixed in 814d160aed6f7e5b0ef25cf38cfa5829a8f551cc
