### ISSUE TITLE
[Pre-Plus] LRZ2 floor flamethrowers are incorrect.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#139]
For some reason, some of the flamethrowers on the ground look like this:

![image](https://user-images.githubusercontent.com/24783625/192656647-c8bd50c4-f601-4fda-8c1d-610edfbd5ca2.png)

when in steam pre-plus, it looks like this:

![image](https://user-images.githubusercontent.com/24783625/192656678-34235e0a-be6c-4d2a-8990-4e9a4ade7042.png)

**Comment by Rubberduckycooly** [comment]
fixed in 036e8746fa2248e7bf99ac2da6c279002baf363f & 1d31ad246225c651125114715eba56ad38241ca9
