### ISSUE TITLE
[Plus] Main menu touch controls muli-select

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/Sonic-Mania-Decompilation#140]
if you highlight exit and then click around this area circled in red, you'll select two (sometimes three) options at once
![image](https://user-images.githubusercontent.com/7158344/192683696-f0d3a216-4fb1-40ff-b91f-b186a10b4f8d.png)

**Comment by Rubberduckycooly** [comment]
fixed in 590c6e087666af1dd28fd1bc813a8d42275a9df1
