### ISSUE TITLE
special stage lag

### ISSUE THREAD

**Issue by KirbyClash** [Rubberduckycooly/Sonic-Mania-Decompilation#142]
the special stage lags can you fix this (and no it's not my pc's gpu)

**Comment by MegAmi24** [comment]
Did you try it on the latest commit of the RSDKv5 decomp? 3D rendering has been optimized a bit since the first release.

**Comment by KirbyClash** [comment]
no not really ill try it now tho

**Comment by KirbyClash** [comment]
it runs at full speed now thanks

**Comment by MaxSnes** [comment]
How can I use commit?

**Comment by MegAmi24** [comment]
You build the decomp yourself
