### ISSUE TITLE
Samsung galaxy tab a6 compatibility plz

### ISSUE THREAD

**Issue by Addy100p** [Rubberduckycooly/Sonic-Mania-Decompilation#143]
This is not really a issue but i want to play the decomp but it is just a black screen with audio and even with the black screen fixes it still shows a black screen so can u plz make the decomp compatible with the samsung galaxy tab a6 soon

**Comment by Addy100p** [comment]
I meant a6 and not s6

**Comment by godreborn** [comment]
from what I understand, this is a known issue.  it happens with my phone, but it doesn't with my mom's.  this is with both my build and the official one.  you'll just have to wait for it to be fixed.

**Comment by Rubberduckycooly** [comment]
known issue. will be fixed eventually.

**Comment by Addy100p** [comment]
I forgot to say this but i can still play the game , i just can not see anything
