### ISSUE TITLE
Inverted UI positions

### ISSUE THREAD

**Issue by Mefiresu** [Rubberduckycooly/Sonic-Mania-Decompilation#144]
"DELETE" and "GAME OPTS." positions are inverted compared to original release.

**Steam**:
![steam](https://user-images.githubusercontent.com/15063879/193444528-f72755b5-c99d-4840-a7f7-5c3b73f7f576.png)

**Decomp**:
![decomp](https://user-images.githubusercontent.com/15063879/193444533-fee1f00b-1c51-48de-9791-2753db4313ac.png)

**Comment by Rubberduckycooly** [comment]
fixed in 86fc1590ad75ffbb1455ef4f2782fa0e7cae9236
