### ISSUE TITLE
(Request) visible gamepad?

### ISSUE THREAD

**Issue by Chonkythiccccc** [Rubberduckycooly/Sonic-Mania-Decompilation#145]
Android user here, managed to get the decomp working on my phone but i realised that although there is a working touchscreen feature there isnt an option to turn into super sonic, since the game activates that on a w key press but there isnt a w key, and the control customisation ingame dosent work for that either. Youtube recommended an app to use a gamepad on but im stupid and dont know how to root my device so i can input on the gamepad, so is there any way i can get a working super sonic activation? Like pressing the jump button twice or smth like that

**Comment by LittlePlanetCD** [comment]
this is already in the works, under the Mania Touch Controls mod.

That will be updated to have visual controls eventually.

**Comment by Chonkythiccccc** [comment]
Thats great
