### ISSUE TITLE
I forget another thing 

### ISSUE THREAD

**Issue by LuigiMan57** [Rubberduckycooly/Sonic-Mania-Decompilation#151]
This is my last message! You either fix it or i will send you to help with the power of my dad!
Do it RDC or RMGRich! Is not that hard! Or i will do it and make a better mania decompilation

**Comment by Chonkythiccccc** [comment]
I sure hope this is a joke or at least a satire post, bcuz the decomp wont function without the data.rsdk file, which you have to BUY from legitimate sites like steam. The devs themselves literally put in big bolded text "do NOT use this as a way to pirate sonic mania", so the devs arent doing anything wrong. If this isnt a joke then youre one of those meme 9y/os lmao
