### ISSUE TITLE
Heavy shinobi boss glitch

### ISSUE THREAD

**Issue by Chonkythiccccc** [Rubberduckycooly/Sonic-Mania-Decompilation#153]
The boss arena loads the area with the capsule, other half of the arena unloads, and the boss proceeds to launch himself into the capsule area which is still inaccessible
![Screenshot_20221008-132222_RSDKv5](https://user-images.githubusercontent.com/114976470/194690153-abf1b98e-f12c-41b4-92c4-5348e384fa1f.jpg)

**Comment by LittlePlanetCD** [comment]
Ultrawide bug. you are on an older version. It has been already fixed.

**Comment by Chonkythiccccc** [comment]
Oh ok
