### ISSUE TITLE
Trouble building v5U - All

### ISSUE THREAD

**Issue by Obspogon** [Rubberduckycooly/Sonic-Mania-Decompilation#159]
Get this error: `The command "copy /Y "C:\Sonic-Mania-Decompilation\build\x64\Release\Game\Game.dll" "C:\Sonic-Mania-Decompilation\build\Game.dll"`

**Comment by Rubberduckycooly** [comment]
that just means it cant copy the dll to the build directory, the dll itself built fine. If the issue persists you can just remove that from post built events.
