### ISSUE TITLE
[All Versions] Restart appears in the Puyo Pause Menu.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#164]
Currently, if you boot into Puyo and pause, you gain the ability to restart.

this is not the behavior of the current steam release of Sonic Mania (where you only have Continue and Exit), and most likely isn't the same behavior for every version.

![image](https://user-images.githubusercontent.com/24783625/196021358-dd27f594-d6d6-45e1-ab41-8e6c1c323683.png)

**Comment by Rubberduckycooly** [comment]
fixed in 09626c79e72124de42edc260343a4cca2af334a2
