### ISSUE TITLE
God morening

### ISSUE THREAD

**Issue by Thehaksisrdcandrmgandmeg0ami** [Rubberduckycooly/Sonic-Mania-Decompilation#166]
I have woke after 1 mom.
Helkon Mister Retro Modern Games and miss rubber-ducky cooly, meg - ami, leon-x and main+metory.
Is block screen fixed already? We is S3&B decompilicione coming out?
Yours traly, the only and most beauful, hudo

No

**Comment by Rubberduckycooly** [comment]
Please stop posting junk shitpost issues. It's really annoying, unhelpful and clogs up the issues page so we can't properly see real issues.
