### ISSUE TITLE
Segfaults on Linux by either restarting or quitting the game (might affect other ports)

### ISSUE THREAD

**Issue by MetalMaxMX** [Rubberduckycooly/Sonic-Mania-Decompilation#170]
I decided to tackle the game and activated debug mode in order to traverse through the special rings in order to practice for each and every one of them in order to route the acquisition of Chaos Emeralds as Sonic & Tails. However, after reaching some point, the game suddenly crashes! Happened within the transition of FBZ1 > 2 and also reliably and consistently happens with either restarting the stage or quitting to the menu through the normal pause screen. I've appended a savefile.bin in case someone can get it to happen, steps I did here were: Play the game normally, get all the Chaos Emeralds (restart a special stage if needed) > Keep playing the game > Encounter the issue.
[SaveData.zip](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/files/9898108/SaveData.zip)

Do tell if I need to do anything more 

Edit: Fixed by PR https://github.com/Rubberduckycooly/RSDKv5-Decompilation/pull/120
Consider closing the issue by merging the PR or reviewing it

**Comment by MGRich** [comment]
PR's been merged.
