### ISSUE TITLE
Disable/Enable Plus

### ISSUE THREAD

**Issue by godreborn** [Rubberduckycooly/Sonic-Mania-Decompilation#182]
where is the flag to disable/enable plus?

**Comment by LittlePlanetCD** [comment]
There is no "flag" to enable plus in the settings of the game, if that's what you're asking.

You have to build the RSDKv5 executable yourself in order to enable the Plus DLC.

**Comment by godreborn** [comment]
no, I can compile it, but I was wondering what exactly determines if it's plus or not.

**Comment by LittlePlanetCD** [comment]
well, if you're building for Windows (as an example), building RSDKv5 with the RSDK_AUTOBUILD flag equal to 1 as a pre-processor definition should turn off Plus on the binary you create.

There's a dev menu flag that can toggle plus too, but that's temporary for the session you have open. It's suggested to do the flag i mentioned on compile

**Comment by LittlePlanetCD** [comment]
the Sonic Mania repository (the one you're in) also has ways to compile Pre-Plus and Plus too, but I'm certain that's not what you're after, right?

**Comment by godreborn** [comment]
which file has that flag?  one of the make files?  I found the option in one of the make files, but it doesn't have 1 or 0 next to it.  it doesn't say anything actually.

**Comment by LittlePlanetCD** [comment]
well, first off, what platform are you building for?

**Comment by godreborn** [comment]
> well, first off, what platform are you building for?

the ps3.  I assumed the way to disable or enable plus was the same across the board.

**Comment by LittlePlanetCD** [comment]
uhh... 

well this is the normal mania decomp repository. the ps3 port of it has nothing to do with this repo and the RSDKv5 decomp repo hosted by RDC here.

if you're doing this for PS3, you want to contact the person who made the PS3 port in the Retro Engine Modding Server discord. There's a dedicated channel in there for the RSDKv5 PS3 port.

**Comment by godreborn** [comment]
> uhh...
> 
> well this is the normal mania decomp repository. the ps3 port of it and RSDKv5 has nothing to do with this repo and the RSDKv5 decomp repo hosted by RDC here.
> 
> if you're doing this for PS3, you want to contact the person who made the PS3 port in the Retro Engine Modding Server discord. There's a dedicated channel in there for the RSDKv5 PS3 port.

my apologies.  I wasn't aware of that discord server.  I am a member of discord though.
