### ISSUE TITLE
Instruction on how to use this on Linux?

### ISSUE THREAD

**Issue by coreybruce** [Rubberduckycooly/Sonic-Mania-Decompilation#188]
Hey I just wanted to for instructions on how to use this on Linux, I don't see a binary file and only see a .so file even if I compile it myself.

**Comment by stxticOVFL** [comment]
This repository only contains the game code, which normally compiles into a dynamic library. The easiest way to compile RSDKv5 + Mania is cloning this repo recursively, obtaining GLFW, libvorbis, libthrora, and other dependencies, and configuring CMake in this repo.

**Comment by coreybruce** [comment]
Ah I see, could you explain that process for me so I do it properly and exactly as you would? :)
