### ISSUE TITLE
"Screen Filter" video setting not persistent

### ISSUE THREAD

**Issue by nickbailuc** [Rubberduckycooly/Sonic-Mania-Decompilation#205]
I prefer using the "clean" filter, rather than "none" (blurry). Everytime I enter the game it is at the "none" setting. None of the other video options seem to reset like that.

The annoying thing is sometimes going to another window and returning, the aspect ratio of RSDK is incorrect and can be fixed by cycling full-screen mode. This solves the issue, but resets the Screen Filter.

Running on Debian 12 (latest stable), KDE, and Wayland. I am compiling the latest git because I am running this on ARM64, and the last release does not work on my x86 machine, something segfaults)

P.S. is there any way to get something like the Scale4x GLSL shader from RetroArch, or does that require a lot of work? I see some mention of other OpenGL/DirectX features in the project, but have no idea how to actually make use of them.

**Comment by LittlePlanetCD** [comment]
Are you setting the screen filter from the dev menu or the Settings Menu in Mania?

**Comment by nickbailuc** [comment]
> Are you setting the screen filter from the dev menu or the Settings Menu in Mania?

settings> options in the game

**Comment by LittlePlanetCD** [comment]
Did you install the correct shaders from the RSDKv5 repository as a mod?

**Comment by nickbailuc** [comment]
> 

no, i was confused how to compile any of it then thought I'd only need what's in this repo and RSDK5 was just for non-mania other games.
Gonna try that right now, im compiling the rsdk5 repo

**Comment by nickbailuc** [comment]
figured out how to install the shaders, however didn't notice if that did anything to the visuals of the game (i'm using the Clean filter anyways) which seemed to be previously available
after installing the shaders as a mod, the filter persists so that solves my problem
