### ISSUE TITLE
Bluetooth controller not recognized (but works in RSDK 3 & 4)

### ISSUE THREAD

**Issue by nickbailuc** [Rubberduckycooly/Sonic-Mania-Decompilation#206]
I'm playing with the SEGA Saturn official Bluetooth controller (OEM by Retro-Bit).

The controller in the system and btctl shows up as "Retro Bit Bluetooth Controller" however the game does not recognize or react to it at all by default (does not show up as an input method in the Options).

RSDK 3 and 4 for Sonic CD, 1, 2 respectively all have worked perfectly out of the box with this controller for a long time on the same system (Debian stable, compiled from latest git).

Currently I'm using AntiMicroX to emulate keyboard buttons with the controller, thanks to the fact that RSDK uses SDL that works, although the blue sphere bonus stages make me think there is considerable input lag.

And thank you for the hard work, I've been enjoying the decompilations for (idk how many) years have passed!!!

**Comment by MegAmi24** [comment]
Please report this in the [RSDKv5 repo](https://github.com/Rubberduckycooly/RSDKv5-Decompilation), not the Sonic Mania repo.
