### ISSUE TITLE
For consideration: removing savestate warning & special stage cheat

### ISSUE THREAD

**Issue by nickbailuc** [Rubberduckycooly/Sonic-Mania-Decompilation#207]
The PC release of the game seems to have been released with a debug feature in the UFO special stage; pressing "W" will increase the Mach speed without having to collect blue spheres. The wiki says it was likely a feature used during testing that they forgot to remove. Perhaps it makes sense to disable this unless running RSDK in debug mode. I am puzzled about whether this is a "feature not a bug" and considered canon lol.

The other small thing would be great to remove the bootup warning about the autosave icon. What I liked about RSDK 3 & 4 is being able to speedup the bootup process and intermission by pressing Backspace. I think RSDK 5 has that only on first boot, which is with debug enabled automatically, however I can't find how to reactivate that after the game creates the save data.

**Comment by MegAmi24** [comment]
This is a decompilation project, which aims to be as accurate as possible to the original game. As such, these features will not be removed. [I've made a mod to remove the autosave popup, though.](https://github.com/MegAmi24/Mania-Decomp-Mods/tree/main/DisableAutoSavePopup)

**Comment by nickbailuc** [comment]
> This is a decompilation project, which aims to be as accurate as possible to the original game. As such, these features will not be removed. [I've made a mod to remove the autosave popup, though.](https://github.com/MegAmi24/Mania-Decomp-Mods/tree/main/DisableAutoSavePopup)

I have a separate question to that, so the debug menu's in Sonic 1,2,CD,Mania were all originally in Christian Whitehead's game? I previously assumed they were added on the decompilations

**Comment by MegAmi24** [comment]
If you're referring to the Dev Menus, they are all in the original versions of the engines too.
