### ISSUE TITLE
Folder Prompt (Android)

### ISSUE THREAD

**Issue by godreborn** [Rubberduckycooly/Sonic-Mania-Decompilation#220]
is this intentional?  is it related to not asking for file and folder permissions at first boot?  a friend wondered if it was possible to disable it or if it was too integrated into the code?  thanks.

**Comment by LittlePlanetCD** [comment]
This is intentional.

**Comment by LittlePlanetCD** [comment]
Also wrong repo lol this is an RSDKv5 android thing, not mania

**Comment by MegAmi24** [comment]
It asks for this so that the decomp isn't tied to a single game environment, instead letting you choose between different ones, such as picking a setup for Sonic Mania or one for Sonic 1. And no, there's no way to disable it, Android's limitations don't allow for that.

**Comment by godreborn** [comment]
alright thanks.  I'll close this now.
