### ISSUE TITLE
Special Stage Boost Crashs the Game

### ISSUE THREAD

**Issue by Gabrizinho** [Rubberduckycooly/Sonic-Mania-Decompilation#237]
When i press ("Y" on xbox/"Triangle" on playstation) in the special stage the game just crash, i tried with the RSDKv5 and RSDKv5U and this bug happens in both

**Comment by MegAmi24** [comment]
Pretty sure this was a bug in the initial release of the decomp that has since been fixed, try building the source code if you haven't yet

**Comment by Gabrizinho** [comment]
Now it's fixed 👌

Em ter., 22 de ago. de 2023 23:11, MegAmi ***@***.***>
escreveu:
