### ISSUE TITLE
Game freezes when collecting question mark powerup in SPZ Encore Mode

### ISSUE THREAD

**Issue by camthehaxman** [Rubberduckycooly/Sonic-Mania-Decompilation#264]
According to gdb, it seems to always be in `Objects/Global/ItemBox.c:ItemBox_GivePowerup()` when I press Ctrl+C during the freeze

Video demonstration: 
https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/assets/155208115/3cc6159d-7b00-4ccc-b322-60bee8f5b51d

Platform: Linux x86-64, GLFW, OpenGL

**Comment by camthehaxman** [comment]
After further testing in gdb, it appears that this loop here https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/blob/master/SonicMania/Objects/Global/ItemBox.c#L608 never exits.

**Comment by MegAmi24** [comment]
Not getting this crash on Windows DX9. Might be platform sepecific.

**Comment by camthehaxman** [comment]
Here is my SaveData.bin file, since that may be relevant.

[SaveData.zip](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/files/14070437/SaveData.zip)

**Comment by GeffDev** [comment]
fwiw, I can only reproduce this bug on cam's save data.

**Comment by LittlePlanetCD** [comment]
> Here is my SaveData.bin file, since that may be relevant.
> 
> [SaveData.zip](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/files/14070437/SaveData.zip)

Your save is just broken. Is this from the steam version, or did this file get created from the decompilation?

**Comment by camthehaxman** [comment]
In what way is it broken? I copied it from the Steam version and then played through encore mode up to this point with the decompilation.

**Comment by LittlePlanetCD** [comment]
> In what way is it broken? I copied it from the Steam version and then played through encore mode up to this point with the decompilation.

From what i can tell, it could potentially be a slight save data problem setup issue, but i'd need to see if this is reproducible on steam. using the save file you provided crashes the steam release the same way, so im wondering what could be happening

**Comment by camthehaxman** [comment]
I tried copying my save file over to the Steam version, and it froze as well, so it doesn't look like this is a bug with the decomp. I still have no idea how this happened.

**Comment by LittlePlanetCD** [comment]
![image](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/assets/24783625/8d091e0d-6925-4e49-a8ab-e7851ac42637)
![image](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/assets/24783625/7b2bee74-c9e1-43e5-8ae8-9296e6385159)

your save data is in an invalid state, you have Tails collected but also not active. you had more than likely broken the save by doing something on the steam version the last time you played.

**Comment by camthehaxman** [comment]
Ok, there must be some other bug that caused this save file inconsistency. I swear I didn't use cheats or mods.
What tool are you using to view that information?

**Comment by LittlePlanetCD** [comment]
i'm using [jcfields' Sonic Mania Save Editor](https://jcfields.gitlab.io/sonic-mania-save-editor/) to view the save data.

You had Tails unlocked at a certain point in your gameplay, so do you remember what happened to him?

**Comment by camthehaxman** [comment]
I do remember using tails in Chemical Plant. I think I died playing as him or something, can't remember. I'll reset back to my original Steam save file (from before I messed with the decomp) and see if I run into this again. I'm going to close this issue for now, unless I figure out a reliable way to reproduce it.

**Comment by Mefiresu** [comment]
For what it's worth, I believe that Steam save files may not be 100% compatible with the decomp because Steam Mania is 32bit and the decomp is usually built for 64bit.
I know for a fact that no special serialization method is done by the game, it's a direct dump of a struct data to a file.
This makes a Steam save file not compatible with big endian platforms such as the Wii/WiiU/PS3.

**Comment by camthehaxman** [comment]
Yeah, I can see that being a problem. We should byte swap on big endian platforms if we want save files to be interchangeable. The `int` type is still 32-bit on most 64-bit platforms, but any struct that's being written should be using the fixed width types, and there shouldn't be any pointers within those structs.
