### ISSUE TITLE
it says: the code execution cannot proceed because msvcp140.dll was not found. even though i have it

### ISSUE THREAD

**Issue by silverhed** [Rubberduckycooly/Sonic-Mania-Decompilation#34]
![Screenshot 2022-08-16 072405](https://user-images.githubusercontent.com/84687911/184797831-a9d7e858-5664-4724-b68d-204eb58d8cd7.png)

**Comment by ActualMandM** [comment]
Make sure Visual C++ redistributables are installed. [x86/32-bit](https://aka.ms/vs/17/release/vc_redist.x86.exe), [x64/64-bit]( https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by Rubberduckycooly** [comment]
Also try downloading it again and let me know if the issue persists. I updated the releas builds about 4 hours after the initial release
