### ISSUE TITLE
Egg Reverie flight when Super with “& Knuckles” mode enabled.

### ISSUE THREAD

**Issue by AbnormalPoof** [Rubberduckycooly/Sonic-Mania-Decompilation#35]
Basically, if you enable & Knuckles mode and transform into super, when you double jump you get Egg Reverie flight instead of the character’s double jump ability.

I tested this on the original game and this isn’t the case.

**Comment by Rubberduckycooly** [comment]
fixed in c1692d057da69df589f5d7d4d49c8428e6f9255d
