### ISSUE TITLE
Encore content unavailable

### ISSUE THREAD

**Issue by scottjco** [Rubberduckycooly/Sonic-Mania-Decompilation#38]
I own this game on Steam, including the plus dlc. I have been unable to figure out how to build it so that it detects this.

**Windows version**

![Capture](https://user-images.githubusercontent.com/59264362/184917472-c02dad4c-bb32-4509-bfed-943e52532ccb.PNG)

**Comment by jackoboDev** [comment]
Meet the same issue. Think it is compilation issue of the current librairies. Need to test that by compiling myself

**Comment by MGRich** [comment]
This is done on purpose. Plus content must be built manually.

**Comment by jackoboDev** [comment]
I compiled the project and now Encore mode is detected with my Steam rsdk file. Just why ? How can you think that people are programmers and have the knowledge to compile your project ?

@scottjco I used MSYS2 on Windows 11 and this command to compile RSDKv5 (https://github.com/Rubberduckycooly/RSDKv5-Decompilation) : make PLATFORM=Windows CC=gcc CXX=g++ $*

**Comment by scottjco** [comment]
> This is done on purpose. Plus content must be built manually.

I assumed as much, and I **have** built it to no avail. I must be doing something wrong. 

I guess I should try jackoboDevs method instead of visual studio

**Comment by ZeptoBST** [comment]
Why not make "SonicMania.exe" a requirement and check if the executable has the encore DLC unlocked? It would be better than forcing everyone to compile it by themselves just to enable Plus mode. Besides, even if you haven't bought the Encore DLC, you can still enable it by compiling it, which is technically an issue.

**Comment by ZeptoBST** [comment]
Seems you're right. I compared both versions and the files are identical. It's controlled by the DLC toggle on Steam. :/
