### ISSUE TITLE
MacOS port?

### ISSUE THREAD

**Issue by mightysashiman** [Rubberduckycooly/Sonic-Mania-Decompilation#39]
Been dreaming of a MacOS port of this game for ages. Might that happen please?
Great job anyway. Thanks you.

**Comment by MGRich** [comment]
We won't publish a Mac port due to how annoying it is to public anything Apple related, but it is possible to both build Mania and RSDKv5 on Mac through the XCode projects.

**Comment by mightysashiman** [comment]
I don't mean to be a nuisance, but I'm not sure I understand "due to how annoying it is to public anything Apple related". I see plenty of ports and utilities that have linux and MacOS build. I'm not sure I get what your are refer to with regards to open source projects. Wouldn't you be mixing up with iOS and app store related stuff maybe? Thanks in advance for your insight.
