### ISSUE TITLE
Sonic and Tails issue

### ISSUE THREAD

**Issue by jackoboDev** [Rubberduckycooly/Sonic-Mania-Decompilation#40]
Sonic can't fly with Tails. He decided to not grab Tails hands. Tested with S&T in GHZ1.

**Comment by ActualMandM** [comment]
Can replicate.

https://user-images.githubusercontent.com/15317421/184988877-2fc03ced-e234-4fd5-b747-42d617fd26e3.mp4

**Comment by Rubberduckycooly** [comment]
fixed in 28a658593ae8b47e5eb209f8ce4c5bbb90a0f75c

**Comment by jackoboDev** [comment]
Can confirm that the issue is solved. Thanks
