### ISSUE TITLE
[Bug] Puyo Puyo match points incorrect

### ISSUE THREAD

**Issue by thetrueyoshifan** [Rubberduckycooly/Sonic-Mania-Decompilation#43]
Very minor thing, but I couldn't find an immediate cause on browsing the source. When playing against a CPU or second player in the standalone Puyo Puyo mode, the points required for the game to end are only set to one, whereas it is a best of three in the vanilla game.

**Comment by Rubberduckycooly** [comment]
should be fixed in 75c87c70e1a735a3aa3b98068ba033cf5a688628
