### ISSUE TITLE
How to enable Sonic Mania Plus mode

### ISSUE THREAD

**Issue by 3doplayer67484** [Rubberduckycooly/Sonic-Mania-Decompilation#44]
Hi I was just wondering on how to enable Sonic Mania Plus mode in the decomp when compiling

**Comment by jackoboDev** [comment]
You must :
-> 1°) buy the game on Steam : https://store.steampowered.com/app/584400/Sonic_Mania/
-> 2°) Compile by yourself the project here to enable Plus Mode if you bought it : https://github.com/Rubberduckycooly/RSDKv5-Decompilation

Autobuild on Github disable the Plus Mode on your RSDK file

**Comment by 3doplayer67484** [comment]
> You must : -> 1°) buy the game on Steam : https://store.steampowered.com/app/584400/Sonic_Mania/ -> 2°) Compile by yourself the project here to enable Plus Mode if you bought it : https://github.com/Rubberduckycooly/RSDKv5-Decompilation
> 
> Autobuild on Github disable the Plus Mode on your RSDK file

Thank you

**Comment by 3doplayer67484** [comment]
I have the game with dlc bought on steam and now I am wondering where the file to enable plus mode is

**Comment by 3doplayer67484** [comment]
Nevermind
