### ISSUE TITLE
Ghost Input with Dualshock 4

### ISSUE THREAD

**Issue by Illidan1943** [Rubberduckycooly/Sonic-Mania-Decompilation#45]
As the title says, whenever I try to use the Dualshock 4 in the decompilation the game starts to behave as if I'm constantly pressing different buttons, it's completely unplayable as I can't even navigate the main menu
Tried several potential solutions including:

- Just plugging in the DS4 with no additional input methods
- DS4Windows
- Steam Input
- Plugging in the controller before and after starting the game
- All of that but wireless
- Uninstalling and reinstalling the drivers
- Restarting PC

Also tried many configurations on DS4Windows, including emulated 360 controller, hiding the DS4, etc, all without avail as the game would continue being unplayable due to the constant ghost input, controller itself is fine as this is the only game that has such issues and nothing indicates any kind of error anywhere else including the official Sonic Mania release where the controller works fine, also checked on https://gamepad-tester.com/ to see any kind of ghost input and as the image indicates everything seems to be working fine
![image](https://user-images.githubusercontent.com/4305249/185182493-0b7ea0b4-5f76-4e37-a604-98a41222f154.png)

I've discarded this being a widespread issue on my system as I've tried with a 360 controller and a Steam controller and the game works fine with those, though not my preferred controllers for this game

**Comment by ActualMandM** [comment]
This is an issue related to the RSDKv5 decomp, as I found out. A workaround for the time being is to use a build from GitHub Actions.
https://github.com/Rubberduckycooly/RSDKv5-Decompilation/issues/25

**Comment by MGRich** [comment]
Reported in https://github.com/Rubberduckycooly/RSDKv5-Decompilation/issues/15.
