### ISSUE TITLE
Egg TV Logo in Weather Mobile Issue

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#46]
The Egg TV logo that appears in the Weather Mobile boss's TV correctly appears and reduces in size. However, instead of moving to the top right and reducing in size at the same time, it reduces in size and stays put in the middle.
Note: The logo appears in the correct spot after the capsule is broken and the TV turns on again for the SPZ-FBZ transition
![h](https://user-images.githubusercontent.com/79285355/185221951-959552da-397c-406b-a106-0377a22e4bdf.png)
.

**Comment by Rubberduckycooly** [comment]
fixed in c6eaeb3180cebd495bd0802f556c91ad945e7a71
