### ISSUE TITLE
Spider Mobile Missing Sound

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#47]
In FBZ's Spider Mobile boss, when you hit the bumper that makes up most of it's body, the bumper sound should play. However, in the decomp, no sound plays.
~~this description feels a bit short but what else am I expected to fit in here~~

**Comment by Rubberduckycooly** [comment]
can't reproduce this one, can you try building the latest commit and reproducing it again? Unsure if it was silently fixed or a bug that only some platforms get

**Comment by RetroForever** [comment]
it seems this bug got silently fixed at some point, ty
