### ISSUE TITLE
Save Select Clear Saves Innacuracy

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#49]
In Steam Mania, when you press up and down to choose a level, but then move out of the select save, it gets reset back to the Clear state. In the decomp, it does not get reset. The only way to reset them is by fully exiting the menu.
![unknown](https://user-images.githubusercontent.com/79285355/185245011-3231a2a1-207e-4b07-b75a-0ce74cdd754c.png)

**Comment by Rubberduckycooly** [comment]
fixed in 5be9e0d6c20b6af34b4b624b080e51f1736ec93b
