### ISSUE TITLE
Act Results UI is off center 

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#51]
Decomp:
![image](https://user-images.githubusercontent.com/24783625/185265885-016e030d-c561-4e4a-8c13-cec547510479.png)
Mania:
![image](https://user-images.githubusercontent.com/24783625/185265953-91233b8a-f479-48b9-af24-7d17dc85ab6d.png)

**Comment by Rubberduckycooly** [comment]
Unable to reproduce. What platform was this on and what was the screen width?

**Comment by LittlePlanetCD** [comment]
this is fixed in latest commits, i'll close the issue.
