### ISSUE TITLE
Control Binding Issues

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#52]
Shift is not accepted anymore in both Main Menu -> Options -> Controls

 Dev Menu -> Options -> Configure Input - Dev Menu -> Options -> Configure Input skips the Up key

**Comment by Rubberduckycooly** [comment]
dev menu fixed in: https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/8e6fcdb919b7682aa87129f7ae27892bad529772
shift, ctrl, alt not working fixed in: https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/5242094286da0bc68c43e65c9d18935d9ab00fd7
