### ISSUE TITLE
SPZ1 Gunner blue missiles

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#55]
SPZ1 Gunner blue missiles returning to sender after hit take about a second longer on average? 5-6 seconds for what should be 4-5 seconds. (was reported, putting it here)

**Comment by LittlePlanetCD** [comment]
Okay, after some actual testing, this seems to indeed be a problem.

Mania : https://cdn.discordapp.com/attachments/800609128561115176/1010470615217602601/SonicMania-SPZ1Boss.mp4

Decomp : https://cdn.discordapp.com/attachments/800609128561115176/1010470749540204644/SMD-SPZ1_Boss.mp4

**Comment by Rubberduckycooly** [comment]
fixed in ac2ca5ce9cc89ac8fba3dab368d10594df42c0e2
