### ISSUE TITLE
ERZ Eggman issues

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#56]
ERZ Eggman smacking arms are sometimes behind him while he does his special dash, should be in front of him.

Eggman's special dash doesn't track Sonic at the top of the screen, and he eventually wraps back around from the bottom

**Comment by Rubberduckycooly** [comment]
fixed in cf9686b65016f6f544fa4bf5d125a5cadd57da56
