### ISSUE TITLE
OOZ2 Fire issue

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#57]
OOZ2 has a bug where if you go into an oil pit (Like at the start) with a fire shield, the explosion sprite that's usually layered behind is actually in front

Mania:
![image](https://user-images.githubusercontent.com/24783625/185266999-1b504491-d3d8-4cf6-8ae0-edf064bd915a.png)

Decomp:
![image](https://user-images.githubusercontent.com/24783625/185267008-03e236c1-93f8-4e07-9620-95f70aeb334b.png)

**Comment by Rubberduckycooly** [comment]
fixed in a11caa6b7578558b0f39a4aa0f734dfce3a1efef
