### ISSUE TITLE
Encore AI issues

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#58]
Holding jump in Encore mode seems to make AI Sonic (and probably other partners?) use their air ability, which doesn't happen in regular Mania.

![image](https://user-images.githubusercontent.com/24783625/185474001-11e60071-1fb4-4b6d-a245-71f2042fd970.png)

**Comment by Rubberduckycooly** [comment]
only applied to sonic since he has a bigger func, the other player's ones are much smaller. regardless, fixed in 7b8db97cd956563d668077aedf1caa0234e6404a
