### ISSUE TITLE
Sonic Mania 1.00 Static Vars are broken

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#61]
![image](https://user-images.githubusercontent.com/24783625/185341216-fb504cbf-f908-4af2-9358-2b088734f56a.png)

funny image moment but u get it rdc

**Comment by Rubberduckycooly** [comment]
fixed in 8712647fa1e87363cb94268bbea697cd617467ee
