### ISSUE TITLE
Player Characters cant immediately walk after looking up

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#62]
the player character is normally able to move to the left or right in mania as soon as they let go of up and press left or right.

here, though, the player has to wait for the character to go back to standing before being able to walk.

Mania:

![SonicMania_2022-08-18_03-37-25](https://user-images.githubusercontent.com/24783625/185351646-dee61f08-6ba0-425d-b629-4d79c439e417.gif)

Decomp:

![RSDKv5U-dx9_64_2022-08-18_03-37-48](https://user-images.githubusercontent.com/24783625/185351765-fbbb59d9-d892-4b3d-aeb1-da0e000c31d5.gif):

**Comment by Rubberduckycooly** [comment]
fixed in de50bd53f3661f45fb43cd065fdc7a35b8812edc
