### ISSUE TITLE
Super Peel Out charging is broken animation wise

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/Sonic-Mania-Decompilation#63]
Mania:
https://user-images.githubusercontent.com/7158344/185469524-d01bb06c-73dc-48c2-8144-7f871813ec6d.mp4

Decomp:
https://user-images.githubusercontent.com/7158344/185469568-17e2cedc-10e2-490a-8ecd-f890825d6d8c.mp4

**Comment by Rubberduckycooly** [comment]
fixed in 677b82284a876a3a90da65ade3c0430bc9c253a1
