### ISSUE TITLE
Menu touch controls visual bug

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/Sonic-Mania-Decompilation#64]
In all menus, using touch controls will enlarge all button icons as if you were hovering over them.
![image](https://user-images.githubusercontent.com/7158344/185470087-cfa354f4-9859-4681-9ff0-712326ebffd8.png)
![image](https://user-images.githubusercontent.com/7158344/185470108-fd04af1d-1cc9-4b5c-9e5e-f4b3a56f3af3.png)

**Comment by Rubberduckycooly** [comment]
fixed in 8712647fa1e87363cb94268bbea697cd617467ee
