### ISSUE TITLE
(1.06, Possibly on older versions?) "CONFIRM" prompt bug.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#65]
the "CONFIRM" prompt to the right doesnt show up when the menu is loaded like in the original, though it does fix itself when hovering another option.

Mania: 

![image](https://user-images.githubusercontent.com/24783625/185473855-c5c57fd0-9fac-46be-b126-3aecca0fe17b.png)

Decomp:

![image](https://user-images.githubusercontent.com/24783625/185473890-2ad94986-c570-47a8-b418-7f20406f4421.png)

**Comment by Rubberduckycooly** [comment]
fixed in 8712647fa1e87363cb94268bbea697cd617467ee
