### ISSUE TITLE
Camera positioning in SSZ2 Last Phase

### ISSUE THREAD

**Issue by stahpittgetzomehelp** [Rubberduckycooly/Sonic-Mania-Decompilation#67]
Upon reaching the final phase of the boss, you are launched from a ramp up into the air which has a set camera position.

The discrepancy here is that the Decomp's camera still follows the player at this point, which is not intended, as it is meant to stay a fixed position.

Mania:
![SSZ2BossCameraMania](https://user-images.githubusercontent.com/36407037/185510875-1717621b-536c-4191-8889-b74dac9221d4.gif)
Decomp:
![SSZ2BossCameraDecomp](https://user-images.githubusercontent.com/36407037/185510894-8987f2a5-84a8-476a-a6a1-4a17595cde23.gif)

**Comment by Rubberduckycooly** [comment]
fixed in 87f0493d244d1d0959a9cd5ca6663be52fecf442
