### ISSUE TITLE
OOZ2 Closed Hatch Bug

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#68]
It's possible to jump through the closed hatches in OOZ2.

![image](https://user-images.githubusercontent.com/24783625/185529454-05c9dcf5-5432-4c01-b3b6-5afe3a1fa612.png)

**Comment by Rubberduckycooly** [comment]
as far as I can tell, steam mania does this too. Please re-open if you can confirm it doesn't.
