### ISSUE TITLE
(OOZ and HCZ) Flume Animation Issues

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#69]
The slides in hydrocity don't activate the flume animation if you're rolling.
And the oil slide quarter pipe tiles in OOZ don't use the flume animation like they should.

**Comment by Rubberduckycooly** [comment]
unable to reproduce, can you get more steps on what to do?

**Comment by LittlePlanetCD** [comment]
Closing this issue, but mainly because RetroForever managed to make a more descriptive issue for both:

https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/issues/77 for OOZ

https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/issues/78 for HCZ
