### ISSUE TITLE
Elaborate which Visual Studio version to use (Windows)

### ISSUE THREAD

**Issue by spaceyspacestar** [Rubberduckycooly/Sonic-Mania-Decompilation#70]
I use windows and wanted to build Sonic Mania but it tells me I need to use v143 to compile. While that's true, I uninstalled VS2022 because I was messing around with MonoGame and wanted to back to VS2019 (all of my uncontinued project were worked from VS2019). I followed the steps but I noticed the issue saying it needs v143. VS2019 uses v142 and below, making me reinstall VS2022 again.

It's not a huge issue but personally it would be nice for people who want to compile but don't know what year of Visual Studio to use.

Thanks for this decomp project by the way!

**Comment by breakthetargets** [comment]
You're able to retarget the solution to v142 and still compile properly.

**Comment by MGRich** [comment]
Should be on RSDKv5 repository instead, as it has the same "issue." Doing a find-all replace-all for `v143` (for VS 2022) and setting it to `v142` (for VS 2019) should work fine, however.
