### ISSUE TITLE
Encore mode breathing SFX is incorrect

### ISSUE THREAD

**Issue by snelson7220** [Rubberduckycooly/Sonic-Mania-Decompilation#71]
In Encore mode the characters normally are supposed to use the Sonic CD drowning sfx instead of the usual drowning jingle, however that same sfx plays during the "breathing" sfx as well, when it should only play during the countdown.

**Comment by Rubberduckycooly** [comment]
fixed in ccf60ee4028ec8e177b16171adc9a082290434af
