### ISSUE TITLE
AIZ Encore: Mighty jumps away from you.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#72]
during the choosing scene, Mighty jumps away from you, when he should be jumping towards you.

Mania, after the jump:
![image](https://user-images.githubusercontent.com/24783625/185640577-8d80a4c3-a7f8-45ca-8d07-0e68bd6a8c31.png)

Decomp, after the jump:

![image](https://user-images.githubusercontent.com/24783625/185640731-3b3027b4-cef4-42be-9707-ef41b35ab4d0.png)

**Comment by Rubberduckycooly** [comment]
fixed in f4e848b41bfe0c4201c359576e63fce3a02c9d7a
