### ISSUE TITLE
AIZ Encore: Plant Based Bugs!

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#73]
The plants that overlay in the stage seem to be a little odd... they don't lock to the bottom edge of the screen.

Sonic Mania:
![image](https://user-images.githubusercontent.com/24783625/185642437-7ebdfc1f-eb79-4618-b81b-b5c62ef5fcff.png)

The decomp:
![image](https://user-images.githubusercontent.com/24783625/185642473-cde7b361-bffb-4b16-92b1-67783f43a902.png)

these are the coords:

![image](https://user-images.githubusercontent.com/24783625/185642613-02f1f237-407e-4ab8-860d-e1c5f5db8968.png)

**Comment by Rubberduckycooly** [comment]
fixed in 29da61cc941cb7077ad5abedd9be7bfc30177730
