### ISSUE TITLE
FBZ Boss Screen Lock Innacuracy

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#75]
In the FBZ Spider Mobile boss fight, the most game breaking of issues presents itself:
the screen lock is one pixel too far down. Absolutely unplayable, I know.
Mania:
![SonicMania_OTqBnrwPdR](https://user-images.githubusercontent.com/79285355/185666803-287c0c45-f765-4a33-9155-d8aab97b440a.png)

Decomp:
![RSDKv5U-sdl2_64_yf9V1bhZl2](https://user-images.githubusercontent.com/79285355/185666847-7796d426-64ef-43be-91ed-db114fec023c.png)

**Comment by RetroForever** [comment]
Note: I've tried to replicate this issue, but it doesn't seem to happen again. Strange one off, or is there more?

**Comment by Rubberduckycooly** [comment]
I found how to replicate this, and it can also happen on mania, meaning it's not a decomp bug. Sorry that mania is now unplayable forever :P
