### ISSUE TITLE
OOZ Smog Issues

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#76]
The smog effect for Oil Ocean Zone Act 2 seems to be distorted in comparison to Mania, looking almost EarthBound like:
Decomp:
![RSDKv5U-sdl2_64_cJVNkbvIje](https://user-images.githubusercontent.com/79285355/185679890-99364ca0-376f-4a45-b876-b33691b07cc9.gif)
 
Mania: 
![SonicMania_0kAwcgnisL](https://user-images.githubusercontent.com/79285355/185679876-86c8cad2-3a5e-408d-bc26-a852109a1b47.gif)

Also, when the smog is in effect, a usually pink color becomes pitch black.
Decomp: 
![decomp](https://user-images.githubusercontent.com/79285355/185680157-1a770492-b6dc-4f6f-86b6-32e8bc7fdbc9.png)

Mania:
![mania](https://user-images.githubusercontent.com/79285355/185680169-59c47815-6402-4b01-9aa7-12bf805464b2.png)

**Comment by Rubberduckycooly** [comment]
fixed in e3a33647ac8a258146454e88bdab8833e93e8a2f
