### ISSUE TITLE
OOZ Oil Slide Issues

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#77]
In Oil Ocean Zone's oil slides, the player does not keep the flume animation upon hitting the flat surface of the slide. In the GIF below, an error with the rotation can also be seen:
![slide](https://user-images.githubusercontent.com/79285355/185680711-2ffa3d6a-d1b5-4bf4-94df-f7ffdaf6da18.gif)
Note: If you walk onto the flat part of the slide, the flume animation does not take effect. It is only kept if you were already in the flume animation triggered by the slope

**Comment by Rubberduckycooly** [comment]
fixed in c625182710afd84fb390ca32b98c2f1fc0e6b570
