### ISSUE TITLE
HCZ Water Slide Issues

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#78]
In Oil Ocean Zone's oil slides, the player can occasionally roll into the slide, and _not_ trigger the flume animation. It seems purely up to chance whether this happens or not, but it certainly can happen.
![wh](https://user-images.githubusercontent.com/79285355/185683951-3f7778e3-cb1f-4d82-abb4-66e79999a8c8.gif)

**Comment by Rubberduckycooly** [comment]
fixed in 1e4ec30b2ea9a681bb930b2374eab4b6d8bd161f
