### ISSUE TITLE
Sonic Mania plus encore mode not working and controls are invisible 

### ISSUE THREAD

**Issue by PauloFelipe262** [Rubberduckycooly/Sonic-Mania-Decompilation#79]
There is no way to play the plus dlc and controls are invisible. And Yes i enabled the mod of controls and still not working of get visible. Can you fix that? Getting an fix update of plus dlc and an visible controls on screen? Without needing an xbox or ps4/ps5 controller?

**Comment by PauloFelipe262** [comment]
My device is a71. I not have lag issues. Only a few in bonus stage that is not the sonic 3 and knuckles based one.

**Comment by MegAmi24** [comment]
You have to build the decomp yourself to get access to the DLC

**Comment by PauloFelipe262** [comment]
But the controls issue?

**Comment by LittlePlanetCD** [comment]
there are no visible controls, if you're playing on a mobile device.

**Comment by Rubberduckycooly** [comment]
the controls may be added in a later update, the controls are invisible for right now.
