### ISSUE TITLE
Android Mediatek devices Just got a black screen with game audio 

### ISSUE THREAD

**Issue by SuperSonic40** [Rubberduckycooly/Sonic-Mania-Decompilation#80]
Mediatek devices when you RUN Sonic mania you Just have a blackscreen with audio

**Comment by LittlePlanetCD** [comment]
this is an RSDKv5 bug, not a Sonic Mania Decompilation bug.

you should be reporting that to here: https://github.com/Rubberduckycooly/RSDKv5-Decompilation
