### ISSUE TITLE
Special Stage Clear: Extra Life Audio bug

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#82]
It is possible to gain an extra life in the Special Stages through Mach Bonuses, which is an intended feature.

However, if you manage to get enough Bonuses to gain an extra life, the decomp will CONSTANTLY repeat the start of the audio file for the 1-Up sound, making a REALLY loud buzzing sound.

https://cdn.discordapp.com/attachments/801312524850167810/1010393004072255493/2022-08-19_22-40-27.mp4

debug was used here to spike up the bonuses high enough but it's possible through normal play.

It might also be possible to do this on other Act Clear Tally's but idk by how much.

**Comment by Rubberduckycooly** [comment]
fixed in 15ecd470bf58247b888334654c5857770530a776
