### ISSUE TITLE
heavy shinobi incorrect behaviour in Titanic Monarch.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#84]
heavy shinobi doesnt do his usual pattern, he just instantly goes into the 8-shot twice.

(reported by Jubba)

**Comment by Rubberduckycooly** [comment]
"intentional" v5U behaviour issue. Not planned to be fixed at this moment, use v5 if you want a fixed version

**Comment by Clownacy** [comment]
Could you elaborate? I'm surprised that RSDKv5U has a backwards-compatibility issue like this.
