### ISSUE TITLE
SPZ 1 Teleporter Collision

### ISSUE THREAD

**Issue by TrackerTD** [Rubberduckycooly/Sonic-Mania-Decompilation#85]
When fired out of the Daytona vans in SPZ1, the player stutters a lot as though the teleporting ring things are coliding with the scenery.
![maniaSPZ1screenshake](https://user-images.githubusercontent.com/71041044/185749268-740a1808-f37a-4884-8ccb-039b06716b64.gif)

**Comment by Rubberduckycooly** [comment]
I'm unable to exactly replicate this one, I think I can replicate it if I manually skip the bit that disables tileCollisions, but I'm unable to replicate it naturally. Is there any other info I should know about it? (is it v5 or v5U? what platform are you playing on? etc)

**Comment by TrackerTD** [comment]
Using V5U, playing on Windows. Tested again this morning - disabled any mods I'd left on and it worked fine, then when I re-enabled the mods it... also worked fine, so I'm genuinely unsure what causes this bug. None of the mods I had active made any changes to SPZ1, or its object code, so I'm very puzzled. 

After a bit of testing, including with mods, the bug did come back - but I'm struggling to isolate what mod could cause it, hence me wondering if it's a decomp bug. Not sure if me accessing SPZ1 via Dev Menu could influence it?

**Comment by TrackerTD** [comment]
![image](https://user-images.githubusercontent.com/71041044/186132696-484d5c69-90da-44df-bb74-698a3ab520cf.png)
I think I've figured out a potential cause - I got it to happen with this Daytona van, but only after _going into the Popcorn Machine that's right before it._ So maybe the Popcorn Machine is doing something wrong?
