### ISSUE TITLE
Cheats are broken (or missing?)

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#86]
A handful of cheats don't seem to work in the level select. Those include:

- 19890501 - unlocks all Medals
- 19790811 - the stealth code
- 6214 - Disable Super Music

the method to get to the level select (if you don't have everything unlocked) also doesnt work.

refer to this guide when using clean save data with the decomp and you'll see what i mean: https://www.youtube.com/watch?v=_sNPFl8CqOY

**Comment by LittlePlanetCD** [comment]
ok

it turns out, the game defaults the debug title screen cheat to _on_ instead of _off_???

it makes the titlescreen cheat do the inverse and turn off the debug mode flag for Save Options

**Comment by Rubberduckycooly** [comment]
do you have mods on? the default for me is debug mode is off
![image](https://user-images.githubusercontent.com/23735543/185879392-d78c6d63-0d41-4b1b-9661-f43e34693393.png)

**Comment by Rubberduckycooly** [comment]
- ricky mode (stealth's cheat) works fine for me, dunno whats wrong there.
- super music disable was broken, its fixed in 20287e1fc792f73b6af39305adbe733455657a00
- nothing seems to be wrong with the unlock everything cheat, fixed up a small issue with globals->superSecret though

**Comment by Rubberduckycooly** [comment]
if everything works now, feel free to close this. Otherwise, I'll need more details on what's wrong specificially

**Comment by LittlePlanetCD** [comment]
i'll do a new build and get to checking this.

i swear, when you have a clean slate the "debug mode" option in save options is not a thing, but when you do the title screen cheat, it appears.

last revision i had, had the title screen cheat in an active state, both with and without dev menu, so i could enter the save options and Debug Mode was visible. Although, when trying to "Activate" the title screen cheat, it removed the option instead, deactivating it.

I'm gonna do a build rn to check everything.

**Comment by LittlePlanetCD** [comment]
Yep, cheats are now fixed and working as intended. 👍
