### ISSUE TITLE
SPZ1 Van Behavior Issue

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#87]
In Mania, the Daytona vans in Studiopolis Zone Act 1 move their whole body down when you step on or inside them, while also tilting to one side or another depending on if the character is standing to the far left or right.
In the decomp, only the tilt behavior is in effect. The body of the car does not move down at all:
Mania: 
![car](https://user-images.githubusercontent.com/79285355/185761183-350c74cd-a1da-4345-b3bc-8f336eb24b23.gif)

Decomp:
![decomp](https://user-images.githubusercontent.com/79285355/185761182-1bef6a1e-73ee-42a6-9f4e-20556b7fa1f1.gif)

**Comment by Rubberduckycooly** [comment]
fixed in e5977134d4958d94927c806d2e8ab0fc11933635
