### ISSUE TITLE
Mighty's Hammer Drop dust doesn't appear in the right place

### ISSUE THREAD

**Issue by jubbalub** [Rubberduckycooly/Sonic-Mania-Decompilation#88]
The dust that appears when Mighty performs the Hammer Drop doesn't appear in the correct place. It appears on the closest solid tiles, instead of where Mighty actually hits. In cases where there are no solid tiles below him, the dust doesn't appear at all.

Mania:
![image](https://user-images.githubusercontent.com/12634749/185768622-1aa4bc65-ee61-477e-a1bf-2f73b3dcc3bf.png)
![image](https://user-images.githubusercontent.com/12634749/185768628-7fd3bea6-7f5e-4f6b-ac26-73cc89a51c97.png)

Decomp:
![image](https://user-images.githubusercontent.com/12634749/185768630-e3876e77-d500-4862-93a9-b92ea12fd6a7.png)
![image](https://user-images.githubusercontent.com/12634749/185768635-7798b721-57eb-4f3e-8417-b5b0fabbf55b.png)

**Comment by Rubberduckycooly** [comment]
fixed in fcf1473beee3c153dbf30923a9fe8321ec653ee7
