### ISSUE TITLE
Flipping signs in SPZ1 only flip one way

### ISSUE THREAD

**Issue by jubbalub** [Rubberduckycooly/Sonic-Mania-Decompilation#89]
The signs in Studiopolis Zone Act 1 can only flip one way, not the other. This is inconsistent with their behavior in Mania, where they can flip both ways. Observed with both horizontal and vertical signs.

Decomp:
![juju1](https://user-images.githubusercontent.com/12634749/185811912-aaf07025-46b5-4965-ad61-958d56c9d664.gif)

Mania:
![jujumania](https://user-images.githubusercontent.com/12634749/185811953-36ffe9fe-ce38-405b-a417-6d09296fceac.gif)

**Comment by Rubberduckycooly** [comment]
fixed in e7b1afdc42459b631f78fe250f3e9c3d6126883e
