### ISSUE TITLE
FBZ2 Incorrect Storm Behavior

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#90]
In this area of FBZ2, the BG and pallete remains stormy. However, in the decomp, it reverts to normal pallete and BG, even though it shouldn't
Mania:
![mania](https://user-images.githubusercontent.com/79285355/185975761-2fa218f7-f045-460f-90b7-5c9c99ce230e.png)
 
 Decomp:
![decomp](https://user-images.githubusercontent.com/79285355/185975782-43c0c6e1-e0d7-41ce-8463-daa9e78e2cf6.png)

**Comment by Rubberduckycooly** [comment]
fixed in 399920938d8a434dd89c473b9bff8e40a669a2e8
