### ISSUE TITLE
Nothing showing up with using mobile version

### ISSUE THREAD

**Issue by Aden-Mystio** [Rubberduckycooly/Sonic-Mania-Decompilation#92]
My phone is a LG Premier pro plus, and with launching RSDKV5/ Sonic Mania (I have mania plus Data.RSDK) I can hear stuff but I can't see anything

**Comment by breakthetargets** [comment]
Already being worked on, also this is a RSDKv5 bug, not a Mania Decomp bug.

**Comment by Aden-Mystio** [comment]
> Already being worked on, also this is a RSDKv5 bug, not a Mania Decomp bug.

Alright then, Thank you
