### ISSUE TITLE
LRZ Fireball Issues

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/Sonic-Mania-Decompilation#94]
In Lava Reef Zone, the fireballs lack collision. Instead of stopping when hitting a wall, they go on without stopping:
![RSDKv5U-sdl2_64_SbQcIuxkwV](https://user-images.githubusercontent.com/79285355/186486687-ba0813fa-5dc1-4e47-8459-3a2a453783f2.png)
It can also cause pretty funny effects, such as vertical fire balls eternally looping from the bottom to the top of the stage:
![RSDKv5U-sdl2_64_VApuwmB5om](https://user-images.githubusercontent.com/79285355/186486858-e314216b-784e-47b9-a163-22f62eb5be00.png)

This is obviously incorrect behavior since Mania has them stop upon impact from a wall.

**Comment by MGRich** [comment]
Does this still happen on current commits?

**Comment by RetroForever** [comment]
...Well, those screenshots were taken with the most recent commit of both the engine and Mania

**Comment by Rubberduckycooly** [comment]
fixed in 5ad33504bd7fdc69993945b1b8a87935e1f4aeb5
