### ISSUE TITLE
HCZ bubbles are very very broken

### ISSUE THREAD

**Issue by NatsumiFox** [Rubberduckycooly/Sonic-Mania-Decompilation#96]
![unknown 1](https://user-images.githubusercontent.com/9996597/186536933-ed980d95-d897-448b-80cc-9aebfbb92fb5.png)

These bubbles give a lot of problems in the decomp. If both the player and sidekick are inside of the bubble, the sidekick can affect the main player's bubble (including allowing it to clip through the ground below!) and not letting them go high enough. I have seen the sidekick's bubble get destroyed, for them to teleport to main player's bubble as well.

Additionally, the sidekick is always able to generate a bubble. This is not how Mania 1.06 works though. In fact, the sidekick is only able to sometimes generate a bubble, and I think it works if there is a bubble object that already exists, but not always. In the decomp, the sidekick *always* generates a bubble.

**Comment by Rubberduckycooly** [comment]
fixed sidekick being able to generate bubbles in 3838cdcd014d2e00ffb9a804735b7c92ac6aef74, unable to replicate the sidekick affecting the player's bubble or anything like that

**Comment by MGRich** [comment]
Please re-open if the second part of the issue persists.

**Comment by NatsumiFox** [comment]
I am unable to check this because when I compile, I get the following error: LNK2001 unresolved external symbol PBL_Player_StageLoad SonicMania (v5U)

**Comment by breakthetargets** [comment]
@NatsumiFox what are you using to build again, because visual studio over here is still working just fine.

**Comment by NatsumiFox** [comment]
Visual Studio.
