### ISSUE TITLE
Boss Music cuts out if a power-up with a dedicated theme ends.

### ISSUE THREAD

**Issue by HarperMarieRose** [Rubberduckycooly/Sonic-Mania-Decompilation#97]
When you're in a boss fight with invincibility, speed shoes, or Super, the boss music will cut out when the power-up ends. Tested on v5U, 64 bit dx9 build on Windows 10.

https://user-images.githubusercontent.com/77728222/186543303-58b6d4c1-c47c-4fcb-b6d4-da309e222c28.mp4

**Comment by Rubberduckycooly** [comment]
Again just to be 100% sure, can you replicate this on the steam version of mania? Music jingles have always been picky in mania

**Comment by HarperMarieRose** [comment]
Just checked on Steam Mania, doesn't cut off there.

**Comment by Rubberduckycooly** [comment]
fixed in d27ed5016a4d42c1126569d2b3f95e4ddefe237d
