### ISSUE TITLE
Player 2 Infinitely Spindashing when trying to jump [Android]

### ISSUE THREAD

**Issue by Swapnekokitten** [Rubberduckycooly/Sonic-Mania-Decompilation#98]
I think this issue only exists within mania mode I think, when player 2 dies, and they respawn and try to jump again, they instead spindash, and if you try to cancel the spindash it just won't, it's like if I was soft locked.
This issue is super annoying I which this to be fixed sooner or later.
Thank you id love to see this bug fixed.

**Comment by breakthetargets** [comment]
Couldn't reproduce.

**Comment by MGRich** [comment]
If someone can reproduce outside of Android/Linux/Switch, I will remove the tag.

**Comment by Swapnekokitten** [comment]
It seems like the issue has been fixed somehow? If someone encounters the same issues somehow feel free to reopen this issue, for now I think it is fixed tails is no longer spindashing infinitely and the problem has been fixed
